-- Get Hostel Occupancy %
CREATE
OR REPLACE FUNCTION FN_GET_HOSTEL_OCCUPANCY (P_HOSTELID INT) RETURNS NUMERIC LANGUAGE plpgsql AS $$
DECLARE
    V_TOTAL_BEDS INT;
    V_OCCUPIED_BEDS INT;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL_BEDS
    FROM BED B
    JOIN ROOM R
        ON B.ROOMID = R.ROOMID
    WHERE R.HOSTELID = P_HOSTELID;

    SELECT COUNT(*)
    INTO V_OCCUPIED_BEDS
    FROM BEDALLOCATION BA
    JOIN BED B
        ON BA.BEDID = B.BEDID
    JOIN ROOM R
        ON B.ROOMID = R.ROOMID
    WHERE R.HOSTELID = P_HOSTELID
      AND BA.ENDDATE IS NULL;

    IF V_TOTAL_BEDS = 0 THEN
        RETURN 0;
    END IF;

    RETURN ROUND(
        (V_OCCUPIED_BEDS::NUMERIC / V_TOTAL_BEDS) * 100,
        2
    );
END;
$$;

-- Get Current Student Bed
CREATE
OR REPLACE FUNCTION FN_GET_CURRENT_BED (P_STUDENTID INT) RETURNS TABLE (
    BEDID BIGINT,
    BEDNUMBER VARCHAR(20),
    ROOMNUMBER VARCHAR(20),
    HOSTELNAME VARCHAR(100)
) LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
    SELECT
        B.BEDID,
        B.BEDNUMBER,
        R.ROOMNUMBER,
        H.HOSTELNAME
    FROM ADMISSION A
    JOIN BEDALLOCATION BA
        ON A.ADMISSIONID = BA.ADMISSIONID
    JOIN BED B
        ON BA.BEDID = B.BEDID
    JOIN ROOM R
        ON B.ROOMID = R.ROOMID
    JOIN HOSTEL H
        ON R.HOSTELID = H.HOSTELID
    WHERE A.STUDENTID = P_STUDENTID
      AND BA.ENDDATE IS NULL;
END;
$$;

--Calculate Laundry Bill
CREATE
OR REPLACE FUNCTION FN_CALCULATE_LAUNDRY_TOTAL (P_LAUNDRYID INT) RETURNS NUMERIC LANGUAGE plpgsql AS $$
DECLARE
    V_TOTAL NUMERIC(10,2);
BEGIN
    SELECT COALESCE(
        SUM(QUANTITY * UNITPRICE),
        0
    )
    INTO V_TOTAL
    FROM LAUNDRYITEM
    WHERE LAUNDRYID = P_LAUNDRYID;

    RETURN V_TOTAL;
END;
$$;

-- Student Outstanding Electricity
CREATE
OR REPLACE FUNCTION fn_get_student_electricity_due (p_studentid INT) RETURNS NUMERIC LANGUAGE plpgsql AS $$
DECLARE
    v_total NUMERIC(10,2);
BEGIN
    SELECT COALESCE(SUM(eb.Amount), 0)
    INTO v_total
    FROM Admission a
    JOIN BedAllocation ba ON a.AdmissionID = ba.AdmissionID
    JOIN Bed b ON ba.BedID = b.BedID
    JOIN Room r ON b.RoomID = r.RoomID
    JOIN ElectricityBill eb ON r.RoomID = eb.RoomID
    WHERE a.StudentID = p_studentid
      AND ba.EndDate IS NULL
      AND eb.Status = ' Pending ';

    RETURN v_total;
END;
$$;

-- Get Student Age
CREATE
OR REPLACE FUNCTION FN_GET_STUDENT_AGE (P_STUDENTID INT) RETURNS INT LANGUAGE plpgsql AS $$
DECLARE
    V_AGE INT;
BEGIN
    SELECT EXTRACT(YEAR FROM AGE(DATEOFBIRTH))
    INTO V_AGE
    FROM STUDENT
    WHERE STUDENTID = P_STUDENTID;

    RETURN V_AGE;
END;
$$;

-- Check Bed Availability
CREATE
OR REPLACE FUNCTION FN_IS_BED_AVAILABLE (P_BEDID INT) RETURNS BOOLEAN LANGUAGE plpgsql AS $$
DECLARE
    V_EXISTS BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1
        FROM BEDALLOCATION
        WHERE BEDID = P_BEDID
          AND ENDDATE IS NULL
    )
    INTO V_EXISTS;

    RETURN NOT V_EXISTS;
END;
$$;